### ISSUE TITLE
phy curation issue, files saved incorrectly

### ISSUE THREAD

**Issue by mariapfj** [CINPLA/expipe-plugin-cinpla#79]
We've increasinlgy noticed the same issues we've had with expipe, where channel_group is spontaneously lost during or after curation, causing downstream scripts to err. In one rec (\\aspasia.ad.fp.educloud.no\ec109\maria\mec-social-nwb\actions\148-201021-2\) I've tried phy_restore, re-registered and spikesorted the rec, and keeping an eye on channel_group during curation to avoid information getting lost, but when I went back to inspect a unit, most (if not all) unsorted units were missing channel_group, and several units previously set as noise were now unsorted (see example image).  I have no clue what could be happening, and we have not been able to restore channel_groups in the instances where only a few key units are missing them.  

this unit was set as noise but changed to unosrted (with the appropriate information being kept in cluster_info.tsv):
![image](https://github.com/user-attachments/assets/946b44d1-30f6-40c5-bceb-ba13c9e654b8)
![image](https://github.com/user-attachments/assets/dd0c77f0-1cda-4941-a134-d1d786631dae)

this unit lost channel_group, among other info, and therefore cannot be saved:
![image](https://github.com/user-attachments/assets/ccfee658-d0f4-4547-879c-e079fa439093)
![image](https://github.com/user-attachments/assets/83425372-f398-45c4-9c73-dbe6edfb8c78)

I realise this is probably a very convoluted issue but I wanted to inform you and hear if you have any inclination as to what's happening?

**Comment by alejoe91** [comment]
Let me try to patch this one. There is a function that re-estimates the channel groups when applying curation [here](https://github.com/CINPLA/expipe-plugin-cinpla/blob/dev/src/expipe_plugin_cinpla/scripts/utils.py#L290), but it's currently run only if spike sorting was not run on groups. I push a fix when this is ran every time there are some missing clusters. Can you send me the phy folder you shared the screenshots for in a zip file?

Note that the groups will be available in the NWB file, but not in Phy since Phy doesn't know how to propagate custom columns after merges/splits
